// MANAGEMENT TYPES
export const GET_MANAGEMENT_DATA = "GET_MANAGEMENT_DATA";
export const MANAGEMENT_DATA_LOADING = "MANAGEMENT_DATA_LOADING";

// AUTH TYPES
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// ERROR TYPES
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// CONTACT TYPES
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";
export const CONTACT_CLEAR = "CONTACT_CLEAR";

// OWNER TYPES
export const GET_OWNER_DATA = "GET_OWNER_DATA";
export const OWNER_DATA_LOADING = "OWNER_DATA_LOADING";

